### PR TITLE
Pull request template and Issue template added.

### PR DESCRIPTION
**Pull request by Shikhar-Raj78**
Issue #181  (Add pr/issue template)

Description:
Add an issue and pr template so contributors are required to follow a predefined style for their pull requests and issues.

Changes:
Added issue template and PR template

#Hacktoberfest

### CODE REVIEW

**Review by mezotv — CHANGES_REQUESTED** [review]
Could you add more types of issues like bug reports, feature requests, etc

**Comment by Shikhar-Raj78** [comment]
@mezotv, I have made the changes you had asked. Please review it.

**Review by mezotv — CHANGES_REQUESTED** [review]
Id remove the performance issue, usability, security ad enhancement template. They don't make much sense for this project

**Comment by Shikhar-Raj78** [comment]
done :)

**Review by mezotv — APPROVED** [review]
LGTM!

**Review by forgetfulskybro — APPROVED** [review]

**Pull request merged**
