### PR TITLE
Add diagram of remake

### PR DESCRIPTION
**Pull request by mezotv**
This adds a diagram to show how the remake is going to work.

Would You Remake

Please let me know what you think!

### CODE REVIEW

**Review by Sans3108 — APPROVED** [review]
Looks good

**Review by 536b656c6c79 — CHANGES_REQUESTED** [review]
I would change out cluster for bot and the wrapping square can be named cluster.

Maybe more vibrant colors? More vibrant background? (Like the one you showed me but then with would you colors?)

**Comment by 536b656c6c79** [comment]
> I would change out cluster for bot and the wrapping square can be named cluster.
> 
> Maybe more vibrant colors? More vibrant background? (Like the one you showed me but then with would you colors?)

Also find a system in colors. This can be useful later on when we scale up more. This is so we know what color corresponds to what type of service. Databases green? caches red? Queue's orange?

**Comment by mezotv** [comment]
> I would change out cluster for bot and the wrapping square can be named cluster.
> 
I called them clusters because the queue system is spread into multiple clusters not multiple bots. So this would make more sense.

**Comment by mezotv** [comment]
> Also find a system in colors. This can be useful later on when we scale up more. This is so we know what color corresponds to what type of service. Databases green? caches red? Queue's orange?

Give me some time and I will be working on a design document with all the colors etc.

**Comment by forgetfulskybro** [comment]
Looks pretty good though maybe we should add descriptions to each box so people will understand what they mean. Anyone else like this idea?

**Comment by mezotv** [comment]
> Looks pretty good though maybe we should add descriptions to each box so people will understand what they mean. Anyone else like this idea? 

I can add that to the design document sure!

**Comment by forgetfulskybro** [comment]
Oops accidentally clicked that button. Meant to put my approval 😄

**Review by forgetfulskybro — APPROVED** [review]

**Pull request closed without merging**
