### PR TITLE
feat: added pre commit hook

### PR DESCRIPTION
**Pull request by Siddharth9890**
## Description
Added pre commit hook using husky to enable conventional messages and also added release action to generate changelog automatically based on message
Issue #188 

## Changes Made
Added actions files in worflow folder
Added pre commit hook and pre message hook using husky

## Additional Notes

hey @mezotv i would suggest you and whole team to check this by cloning it locally and testing.

### CODE REVIEW

**Comment by mezotv** [comment]
Hey @Siddharth9890, I had a question regarding husky, how does it work for people using GitHub desktop instead of the GitHub cli?

**Comment by Siddharth9890** [comment]
It should work because husky works on git. Honestly lot of people use git
CLI or git integrated in vscode husky works for both of them. Not sure
about github desktop though

**Comment by Siddharth9890** [comment]
hey @mezotv how is the husky looking good?

**Comment by mezotv** [comment]
> hey @mezotv how is the husky looking good?

Yea looks good so fsr just looking to get s review drom @forgetfulskybro before merging.

**Review by mezotv — APPROVED** [review]
Looks good to me!

**Review by mezotv — CHANGES_REQUESTED** [review]
I just tested it with GitHub desktop and it doesn't seem to work, Do you know if there is a  fix for this error? 
image

**Review by forgetfulskybro — CHANGES_REQUESTED** [review]
I too got an error using GitHub Desktop. 
image

**Comment by Siddharth9890** [comment]
one a serious note @mezotv why to use github desktop when we can use tools like git cli or vs code integration with git cli. Most of seniors developers i seen use cli or vs code integration? And secondly for the errors for @forgetfulskybro [refer here it is windows error nothing to do with husky i beileve](https://stackoverflow.com/questions/74387008/cygwin-warning-couldnt-comute-fast-cwd) and for @mezotv for your error make sure to reinstall node modules so that pre install script will work. I dont use windows anymore so i can't replicate it in windows system

**Comment by mezotv** [comment]
> one a serious note @mezotv why to use github desktop when we can use tools like git cli or vs code integration with git cli. Most of seniors developers i seen use cli or vs code integration? 

Its just a lot easier to use and more convinient. Im fine with switching to just the github cli but I dont think all our staff are gonna switch any time soon.

**Comment by Siddharth9890** [comment]
Then i cant resolve those errors as i dont have a windows machine it looks like some packages missing from windows os for husky to work i have no idea on that @mezotv

**Comment by forgetfulskybro** [comment]
> And secondly for the errors for @forgetfulskybro [refer here it is windows error nothing to do with husky i beileve](https://stackoverflow.com/questions/74387008/cygwin-warning-couldnt-comute-fast-cwd) 

Only got this error when downloading your commit and in the error it says it's coming from husky at the bottom.

**Comment by Siddharth9890** [comment]
hey @forgetfulskybro if you read the complete error message it clearly says that it could not compute the FAST_CWD pointer and that;s why husky failed if you google it it will show results to update git version. That's why husky failed.

**Pull request closed without merging**
